# Generated by Django 4.1.8 on 2023-04-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizz',
            old_name='description',
            new_name='tags',
        ),
    ]
