# Generated by Django 4.1.7 on 2023-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_remove_quizz_quizz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
