# Generated by Django 4.1.8 on 2023-04-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_rename_description_quizz_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='comment',
            new_name='tags',
        ),
    ]
