# Generated by Django 4.1.8 on 2023-04-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_rename_comment_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
    ]
